name: autorola_assignment
description: autorola-assignment
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api:
    path: ./api
  flutter:
    sdk: flutter

  # Common
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_route: ^7.1.0
  flutter_translate: ^4.0.2
  package_info_plus: ^4.0.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.0.3

  # TODO: Project dependent remove if not needed
  # Auth
  flutter_secure_storage: ^8.0.0 # Required android manifest minSdkVersion of 18 (Can be 16 if removed)
  synchronized: ^3.1.0

  # TODO: Keep if image picking is needed
  image_picker: ^0.8.7+5
  permission_handler: ^10.0.0

  # Misc
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4 # All google fonts
  firebase_crashlytics: ^3.3.1
  firebase_core: ^2.13.0
  universal_platform: ^1.0.0+1
  dio: ^5.0.0
  internet_connection_checker_plus: ^2.0.0
  multiselect: ^0.1.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  auto_route_generator: ^7.0.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  freezed: ^2.3.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon-ios.png"
  adaptive_icon_foreground: "assets/icons/icon-android.png"
  adaptive_icon_background: "#66a7f0"

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/data/
    - assets/images/
    - assets/flags/
