// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA2KoJwE5spY6_RP3zCE0uFxAOHZGDhrg',
    appId: '1:732870131391:web:6ced92bb1e2a70a63c100a',
    messagingSenderId: '732870131391',
    projectId: 'flutter-template-75c5f',
    authDomain: 'flutter-template-75c5f.firebaseapp.com',
    storageBucket: 'flutter-template-75c5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiHLcUDTL7r_mFpPJOiqrduaBO3EcgY8',
    appId: '1:732870131391:android:9c21b010522141143c100a',
    messagingSenderId: '732870131391',
    projectId: 'flutter-template-75c5f',
    storageBucket: 'flutter-template-75c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OlWmHB5UpGJG2i0q_l_SI8EBgWggBDw',
    appId: '1:732870131391:ios:0380ceb48059e3843c100a',
    messagingSenderId: '732870131391',
    projectId: 'flutter-template-75c5f',
    storageBucket: 'flutter-template-75c5f.appspot.com',
    iosClientId: '732870131391-qtohgaubl31u7o5ba0ntni7pr8ast6ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.template',
  );
}
