default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play internal track"
  lane :deploy_internal do
    upload_to_play_store(
      track: 'internal', 
      release_status: 'draft',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end